class CfgPatches
{
	class Japanese_Fonts
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Data_F","A3_UiFonts_F"};
	};
};

class CfgFontFamilies
{
	class EtelkaMonospacePro
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
	};
	class EtelkaMonospaceProBold
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold6",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold7",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold8",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold9",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold10",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold11",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold12",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold13",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold14",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold15",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold16",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold17",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold18",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold19",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold20",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold21",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold22",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold23",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold24",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold25",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold26",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold27",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold28",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold29",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold30",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold31",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold34",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold35",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold37",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold46"
		};
	};
	class EtelkaNarrowMediumPro
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
		spaceWidth = 0.9;
		spacing = 0.17;
	};
	class PuristaBold
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold6",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold7",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold8",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold9",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold10",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold11",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold12",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold13",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold14",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold15",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold16",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold17",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold18",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold19",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold20",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold21",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold22",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold23",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold24",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold25",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold26",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold27",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold28",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold29",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold30",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold31",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold34",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold35",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold37",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold46"
		};
	};
	class PuristaLight
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
	};
	class PuristaMedium
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
	};
	class PuristaSemibold
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold6",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold7",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold8",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold9",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold10",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold11",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold12",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold13",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold14",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold15",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold16",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold17",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold18",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold19",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold20",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold21",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold22",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold23",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold24",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold25",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold26",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold27",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold28",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold29",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold30",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold31",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold34",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold35",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold37",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold46"
		};
	};
	class RobotoCondensed
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
	};
	class RobotoCondensedBold
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold6",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold7",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold8",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold9",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold10",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold11",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold12",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold13",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold14",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold15",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold16",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold17",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold18",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold19",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold20",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold21",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold22",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold23",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold24",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold25",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold26",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold27",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold28",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold29",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold30",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold31",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold34",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold35",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold37",
			"\JP_uifonts_data\fonts\NotoSansCJK-Bold46"
		};
	};
	class RobotoCondensedLight
	{
		fonts[] =
		{
			"\JP_uifonts_data\fonts\NotoSansCJK6",
			"\JP_uifonts_data\fonts\NotoSansCJK7",
			"\JP_uifonts_data\fonts\NotoSansCJK8",
			"\JP_uifonts_data\fonts\NotoSansCJK9",
			"\JP_uifonts_data\fonts\NotoSansCJK10",
			"\JP_uifonts_data\fonts\NotoSansCJK11",
			"\JP_uifonts_data\fonts\NotoSansCJK12",
			"\JP_uifonts_data\fonts\NotoSansCJK13",
			"\JP_uifonts_data\fonts\NotoSansCJK14",
			"\JP_uifonts_data\fonts\NotoSansCJK15",
			"\JP_uifonts_data\fonts\NotoSansCJK16",
			"\JP_uifonts_data\fonts\NotoSansCJK17",
			"\JP_uifonts_data\fonts\NotoSansCJK18",
			"\JP_uifonts_data\fonts\NotoSansCJK19",
			"\JP_uifonts_data\fonts\NotoSansCJK20",
			"\JP_uifonts_data\fonts\NotoSansCJK21",
			"\JP_uifonts_data\fonts\NotoSansCJK22",
			"\JP_uifonts_data\fonts\NotoSansCJK23",
			"\JP_uifonts_data\fonts\NotoSansCJK24",
			"\JP_uifonts_data\fonts\NotoSansCJK25",
			"\JP_uifonts_data\fonts\NotoSansCJK26",
			"\JP_uifonts_data\fonts\NotoSansCJK27",
			"\JP_uifonts_data\fonts\NotoSansCJK28",
			"\JP_uifonts_data\fonts\NotoSansCJK29",
			"\JP_uifonts_data\fonts\NotoSansCJK30",
			"\JP_uifonts_data\fonts\NotoSansCJK31",
			"\JP_uifonts_data\fonts\NotoSansCJK34",
			"\JP_uifonts_data\fonts\NotoSansCJK35",
			"\JP_uifonts_data\fonts\NotoSansCJK37",
			"\JP_uifonts_data\fonts\NotoSansCJK46"
		};
	};
};